id: hl7.fhir.us.pq-cmc
canonical: http://hl7.org/fhir/us/pq-cmc
name: FHIR_pqcmc
title: "PQ/CMC FHIR Implementation Guide"
description:  guide to submitting PQ/CMC data for exchanged in FHIR resources.
status: draft
license: CC0-1.0 #https://www.hl7.org/fhir/valueset-spdx-license.html
version:  0.1.5
fhirVersion: 5.0.0-ballot
# fhirVersion: 5.0.0
copyrightYear: 2021+
releaseLabel: Build CI
publisher:
  name: HL7 International - Biomedical Research and Regulatory WG
  url: http://www.hl7.org/Special/committees/rcrim/index.cfm
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
menu:
  Home: index.html
  Table of Contents: toc.html
  eCTD Profiles:
    eCTD Product Description and Composition of the Drug Product: eCTD32P10.html 
    eCTD Product Batch Formula: eCTD32P32.html 
    eCTD Product Characterization of Impurities: eCTD32P55.html 
    eCTD Product Container Closure System: eCTD32P70.html 
    eCTD Substance General Information: eCTD32S10.html 
    eCTD Substance Control of Materials: eCTD32S23.html 
    eCTD Substance Characterisation: eCTD32S30.html 
    eCTD Substance Container Closure System: eCTD32S60.html 
    eCTD Specification: eCTDSP4151.html 
    eCTD Batch Analyses: eCTDSP4454.html 
    eCTD Stability Data: eCTDSP7383.html
  General Instructions: instruction.html
  Artifacts: artifacts.html
  Downloads: downloads.html
  Change Notes: change_notes.html

pages:
  index.md:
    title: Home
  eCTD32P10.md:
     title: Product Description and Composition of the Drug Product
  eCTD32P32.md:
     title: Product Batch Formula
  eCTD32P55.md:
     title: Product Characterization of Impurities
  eCTD32P70.md:
     title: Product Container Closure System
  eCTD32S10.md:
     title: Substance General Information
  eCTD32S23.md:
     title: Substance Control of Materials
  eCTD32S30.md: 
     title: eCTD Substance Characterisation
  eCTD32S60.md:
     title: Substance Container Closure System
  eCTDSP4151.md:
     title: Specification
  eCTDSP4454.md:
     title: Batch Analyses
  eCTDSP7383.md:
     title: Stability Data
  instruction.md:
    title: General Instructions
  downloads.md:
    title: Downloads
  change_notes.md:
    title: Change Notes
parameters:
 excludettl: true
 excludemap: 'true'
#   validation: [allow-any-extensions, no-broken-links]