id: hl7.fhir.us.pq-cmc
canonical: http://hl7.org/fhir/us/pq-cmc
name: FHIR_pqcmc
title: "PQ/CMC FHIR Implementation Guide"
description:  guide to submitting PQ/CMC data for exchanged in FHIR resources.
status: draft
license: CC0-1.0 #https://www.hl7.org/fhir/valueset-spdx-license.html
version:  0.1.10
#fhirVersion: 5.0.0-snapshot4
#fhirVersion: 5.0.0
fhirVersion: 5.0.0-snapshot3
copyrightYear: 2021+
releaseLabel: Build CI
publisher:
  name: HL7 International - Biomedical Research and Regulatory WG
  url: http://www.hl7.org/Special/committees/rcrim/index.cfm
jurisdiction: urn:iso:std:iso:3166#US "United States of America"
menu:
  Home: index.html
  Table of Contents: toc.html
  eCTD Profiles:
    Product Description and Composition of the Drug Product (3.2.P.1.0): eCTD32P10.html 
    Product Batch Formula (3.2.P.3.2): eCTD32P32.html 
    Product Characterization of Impurities (3.2.P.5.5): eCTD32P55.html 
    Product Container Closure System (3.2.P.7.0): eCTD32P70.html 
    Substance General Information (3.2.S.1.0): eCTD32S10.html 
    Substance Control of Materials (3.2.S.2.3): eCTD32S23.html 
    Substance Characterisation (3.2.S.30.): eCTD32S30.html 
    Substance Container Closure System (3.2.S.6.0): eCTD32S60.html 
    Specification (3.2.S.4.1, 3.2.P.4.1 & 3.2.P.5.1): eCTDSP4151.html 
    Batch Analyses (3.2.S.4.4 & 3.2.P.5.4): eCTDSP4454.html 
    Stability Summary (3.2.S.7.1 & 3.2.P.8.1): eCTDSP7181.html
    Stability Data (3.2.S.7.3 & 3.2.P.8.3): eCTDSP7383.html
  General Instructions: instruction.html
  Artifacts: artifacts.html
  Downloads: downloads.html
  Change Notes: change_notes.html

pages:
  index.md:
    title: Home
  eCTD32P10.md:
     title: Product Description and Composition of the Drug Product
  eCTD32P32.md:
     title: Product Batch Formula
  eCTD32P55.md:
     title: Product Characterization of Impurities
  eCTD32P70.md:
     title: Product Container Closure System
  eCTD32S10.md:
     title: Substance General Information
  eCTD32S23.md:
     title: Substance Control of Materials
  eCTD32S30.md: 
     title: eCTD Substance Characterisation
  eCTD32S60.md:
     title: Substance Container Closure System
  eCTDSP4151.md:
     title: Specification
  eCTDSP4454.md:
     title: Batch Analyses
  eCTDSP7181.md:
     title: Stability Summary
  eCTDSP7383.md:
     title: Stability Data
  instruction.md:
    title: General Instructions
  downloads.md:
    title: Downloads
  change_notes.md:
    title: Change Notes
parameters:
 excludettl: true
 excludemap: 'true'
#   validation: [allow-any-extensions, no-broken-links]